version: '3'

services:
  db:
    image: mariadb:10.6
    volumes:
      - database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}

  php:
    depends_on:
      - db
    build:
      context: ./.boing/docker/php
    volumes:
      - .:/srv

  web:
    depends_on:
      - php
    build:
      context: ./.boing/docker/nginx/prestashop
    volumes:
      - .:/srv
