FROM nginx:1.25-alpine

ENV root "/srv/public"
ENV index "index.php"
ENV fastcgi_pass "php:9000"

ADD ./default.conf /etc/nginx/conf.d/default.template

CMD sh -c "envsubst \"`env | awk -F = '{printf \" \\\\$%s\", $1}'`\" < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
